### ISSUE TITLE
Order of Parks-McClellan Filter

### ISSUE THREAD

**Issue by transpersonify** [eglerean/funpsy#1]
Hi there,
Kudos for sharing your code online! I am trying to apply bandpass filter to the regional BOLD time-series (on the mean timeseries of ROIs rather than voxel-wise timeseries), I applied Parks-McClellan Filter, however, optimal order determined by firpmord is 54. At this order, my timeseries amplitude varies at the order of 10^64 ! which is definitely an error. Can you please let me know what should be the optimal band-pass filter design for filtering the data in the narrow-band 0.04-0.07Hz? Thanks!

**Comment by eglerean** [comment]
Hi! 

I can't test things today, but you could email me one time series so that I could try it locally. In general, the time series should be "long enough" (rule of thumb is > 4 times filter order). Also make sure you remove the mean before filtering. Other filters (e.g. IIR) are also an option, since they are a good trade-off when time series are too short.

**Comment by transpersonify** [comment]
>  the time series should be "long enough" (rule of thumb is > 4 times filter order).

Yes this condition is met. 

> Also make sure you remove the mean before filtering

Do you mean temporal mean (mean of signal amplitudes at each timepoints) or spatial mean (TS averaged across all regions)?

I think the problem was that I did not remove transients. After removing transients it looks okay. However, I would want to know the answers to the previous question.

Thanks so much again.

**Comment by eglerean** [comment]
Hi

yes I meant temporal mean, sorry for not being clear. A bandpass filter stops the frequency at 0 HZ (i.e. the mean), but in practice due to filter implementations that happens only after filter transient (buffer of the filter is initialized with zeros). So by removing the temporal mean, you help the filter doing a better job. :)

cheers
Enrico

**Comment by transpersonify** [comment]
Thanks so much I should try that.
